# https://<yourhostname>:3000

services:
    wireshark:
        cap_add:
            - NET_ADMIN
        container_name: wireshark
        dns: 10.3.1.4
        dns_search:
            - ubuntu.home
            - home
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - SSLKEYLOGFILE=/home/wireshark/sslkeyfile.log
        image: s2.ubuntu.home:5000/docker.io/linuxserver/wireshark:4.0.14
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
#       network_mode: host
        networks:
            - wireshark-net
        ports:
          - "3000:3000"
          - "3001:3001"
        restart: unless-stopped
        volumes:
            - ./:/home/wireshark

networks:
    wireshark-net:
        name: wireshark-container-net
